package com.potetm;

public class MusicFiles {
    public static final String[] MUSIC_FILES = {"/Users/potetm/Music",
            "/Users/potetm/Music/.localized",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/.DS_Store",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/01 - Girl Talk - Oh No.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/02 - Girl Talk - Let It Out.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/03 - Girl Talk - That's Right.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/04 - Girl Talk - Jump on Stage.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/05 - Girl Talk - This Is the Remix.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/06 - Girl Talk - On and On.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/07 - Girl Talk - Get It Get It.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/08 - Girl Talk - Down for the Count.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/09 - Girl Talk - Make Me Wanna.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/10 - Girl Talk - Steady Shock.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/11 - Girl Talk - Triple Double.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/12 - Girl Talk - Every Day.mp3",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/All Day - Album Cover.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/All Day - Back Cover.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/Insert 1.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/Insert 2.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/Insert 3.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Album Artwork/Insert 4.jpg",
            "/Users/potetm/Music/Girl Talk - All Day (IA123)/Info.rtf",
            "/Users/potetm/Music/iTunes",
            "/Users/potetm/Music/iTunes/Album Artwork",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/04",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/04/02",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/04/02/10",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/08",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/08/00",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/08/00/06",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/08/00/06/4A29F979F0E695CC-93D24562BEAD7608.itc",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/10",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/10/11",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/10/11/10",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/14",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/14/01",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/14/01/11",
            "/Users/potetm/Music/iTunes/Album Artwork/Cache/4A29F979F0E695CC/14/01/11/4A29F979F0E695CC-0B8F3CA4EF566B1E.itc",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/01",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/01/04",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/01/04/04",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/01/04/04/045B8AFB29E48A3441-621FE2B2FF08F738.itc",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/10",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/10/14",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/10/14/03",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/10/14/03/03E443A06150D693EA-B9D2318C91CE93DF.itc",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/15",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/15/15",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/15/15/11",
            "/Users/potetm/Music/iTunes/Album Artwork/Cloud Purchases/4A29F979F0E695CC/15/15/11/113920A3BD5FA11BFF-68AAAECA271C5705.itc",
            "/Users/potetm/Music/iTunes/Album Artwork/Download",
            "/Users/potetm/Music/iTunes/iTunes Library Extras.itdb",
            "/Users/potetm/Music/iTunes/iTunes Library Genius.itdb",
            "/Users/potetm/Music/iTunes/iTunes Library.itl",
            "/Users/potetm/Music/iTunes/iTunes Media",
            "/Users/potetm/Music/iTunes/iTunes Media/.iTunes Preferences.plist",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ar.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ca.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/cs.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/da.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/Dutch.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/el.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/en_GB.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/English.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/fi.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/French.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/German.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/he.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/hr.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/hu.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/id.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/Italian.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/Japanese.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ko.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ms.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/no.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/pl.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/pt.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/pt_PT.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ro.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/ru.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/sk.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/Spanish.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/sv.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/th.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/tr.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/uk.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/vi.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/zh_CN.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Automatically Add to iTunes.localized/.localized/zh_TW.strings",
            "/Users/potetm/Music/iTunes/iTunes Media/Downloads",
            "/Users/potetm/Music/iTunes/iTunes Media/Music",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/01 Oh No.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/02 Let It Out.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/03 That's Right.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/04 Jump on Stage.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/05 This Is the Remix.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/06 On and On.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/07 Get It Get It.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/08 Down for the Count.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/09 Make Me Wanna.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/10 Steady Shock.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/11 Triple Double.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Girl Talk/All Day/12 Every Day.mp3",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/01 Intro.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/02 Just Gettin' Started.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/03 The Lesson.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/04 Push On.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/05 Truth Be Told.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/06 Place to Be.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/07 Night to Remember.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/08 Walk In the Park.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/09 Gifted.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/10 They Call Me.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/11 Life & Rhymes.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/12 True Indeed.m4a",
            "/Users/potetm/Music/iTunes/iTunes Media/Music/Surreal & The Sound Providers/True Indeed/13 The Rundown.m4a",
            "/Users/potetm/Music/iTunes/iTunes Music Library.xml",
            "/Users/potetm/Music/iTunes/sentinel"
    };
}
